### ISSUE TITLE
Audit Pending and Clearance Pending State

### ISSUE THREAD

**Issue by mrajayp** [onaio/tally-ho#162]
*Status: This functionality does not exist*

When an audit record is marked as requiring a field audit, or a new form from the field, then the record is move to a new state - for Audit - Audit Pending State and for Clearance - Clearance Pending State. Currently these forms immediately move to data entry 1 state.

**Comment by pld** [comment]
listed under 1.14

**Comment by JohnMwashuma** [comment]
I think the current state of the system has fixed this issue.
New forms from clearance are assigned `Clearance State` and for audit records `Audit State`. No form from the above scenario's is sent to data entry 1 state. @pld Am i correct?

**Comment by pld** [comment]
Cool, that includes the first scenario mentioned, when "an audit record is marked as requiring a field audit", they stay in the `Audit State`?

If the above is true, please close this issue

**Comment by JohnMwashuma** [comment]
Good question. So i went ahead and tested scenario two and it needs a fix. 

### Current behaviour:
When an audit record is being reviewed and the option `Request Audit Action from field` under `Action prior to recommendation:` section is selected and the button `Mark Form as Resolved` is clicked. The form is sent to `Data Entry 1` state.  
### Expected behaviour:
The form should still remain in `Audit State` and not move to `Data Entry 1` state.

**Comment by JohnMwashuma** [comment]
@pld When we say `Audit Pending State` are we referring to what we currently have `Audit State` ? or do we need to create a new state for this? Same with `Clearance Pending State`

**Comment by pld** [comment]
Don't think we should need any new states for this
