### ISSUE TITLE
Add the expected location of the form in clearance section

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#210]
Record previous form location/state before resetting to clearance state.
Related to #185

**Comment by JohnMwashuma** [comment]
Do we still need to record the previous form location/state before sending it to clearance?. Am asking this because the use case for this was as follows:

`In the case there are duplicate forms, the first form may already have started to be processed before the second form is attempted at intake. In this case, we would need to track down the second form and retrieve it to clearance. Accordingly, knowing what stage the form is, is important.
`

 The current state of the system does not allow form duplicates i.e there is no way a form duplicate can happen either from creating a new form or intaking a form. That said, do we still need to implement this issue? because i don't see the use case for this now.

 @pld @akahure  your opinion on this please.

**Comment by JohnMwashuma** [comment]
From my comment on a related issue https://github.com/onaio/tally-ho/issues/185#issuecomment-454369366, i have realised this issue is still relevant.

**Comment by akahure** [comment]
My thoughts are that we need to implement it because the requirements states: 
_Where two forms are attempted to be in-taken into the system against the same centre and station and race, the issue should be raised to clearance as “duplicate forms” and **both forms should be electronically passed to the clearance stage.** The screen shall display the entered form details, including the barcode._
In this case we should accept both forms and not reject during intake.

**Comment by JohnMwashuma** [comment]
@akahure Yeah that's correct, my previous comment was misleading. Will be implemented as per requirements
