### ISSUE TITLE
Implement a way to set user timeout from the GUI.

### ISSUE THREAD

**Issue by JohnMwashuma** [onaio/tally-ho#252]
Relate to #243

**Comment by akahure** [comment]
Suggested that we do this per role and the Admin should be the one to set this.
- Do we set this by Minutes/ Hours ?
- Suggestion is we set this by Role and not by User 
- What happens when a user is in the middle of DE and they need to login again because of timeout, and they will need login again and enter the barcode for the form once more.
Need to check if once a user is logged out, will they need to login again and enter the same Barcode if for instance they were doing DE1?

**Comment by JohnMwashuma** [comment]
Related issue: https://github.com/onaio/tally-ho/issues/20

**Comment by JohnMwashuma** [comment]
Investigate why after session time out during data entry, when the session is renewed a 404 error is thrown.

**Comment by JohnMwashuma** [comment]
Currently user session timeout is set to one hour of idle time, going to make this configurable and set it per user group.

**Comment by pld** [comment]
@JohnMwashuma this does not need to be per user, just 1 value that applies to everyone.

- Units for this value that make sense are probably hours and accepting decimals, we don't need to ask HNEC, we can dictate.
- The timeout is based on inactivity, right? So this would only logout a user in the middle of data entry if they take that amount of time between a step that reloads the page, if this is set an hour or higher that shouldn't happen -- but we should be clear about how this works in the docs.

**Comment by JohnMwashuma** [comment]
@pld So the current timeout value which applies to every user is 60minutes/1hour, currently this is hard corded and not documented. So from your suggestion this value will be updated/set from the GUI right?, so in that case, what will this value be tied to when set? i.e. where will we be storing this value, because having it per user group made sense in that the value can be retrieved from the user group model.

**Comment by pld** [comment]
since dynamic somewhere in the database, do we have something appropriate for metadata like this?

if not we can add a config of metadata table for dynamic site configuration values like this

**Comment by moshthepitt** [comment]
@JohnMwashuma @pld  since this project uses [django.contrib.sites](https://github.com/onaio/tally-ho/blob/master/tally_ho/settings/common.py#L34), it is possible to tie global "settings" to the Site model.

Although, since we dont want to update the Site model directly we'd end up with something like this:

```python
class SiteInfo(models.Model):
    site = models.OneToOneField(Site)  # links to the Site model
    # other fields

# then we'd need a signal like so

@receiver(post_save, sender=Site)
def create_site_info_object(sender, instance, created, **kwargs):
    if created or not instance.siteinfo:
        site_info, site_info_created = SiteInfo.objects.get_or_create(site=instance)
```

**Comment by pld** [comment]
Cool, that looks like a good approach

**Comment by JohnMwashuma** [comment]
Thanks @moshthepitt
